#ifndef SYSCALLCOMMONHEADER
#define SYSCALLCOMMONHEADER



#define FL_PRINTALLFILES 0x1
#define FL_PRINTALLEXEC 0x2
#define FLAG_PRINTALLFILES(x) ((x) && FL_PRINTALLFILES)
#define FLAG_PRINTALLEXEC(x) ((x) && FL_PRINTALLEXEC)
#endif
