---
# Variables used to provision EC2 instances
ec2_config:
  region: us-east-1
  keypair_name: default # will end up being unused
  instance_type: t2.micro
  image: ami-0ca3e3965ada31684
  vpc_subnet_id: 
  assign_public_ip: yes
  instance_tag_name: RDCB
  ansible_password: ab12AB!@

# maybe put in vault? We should change this
